name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: bladedown

      - name: Download test environment
        run: |
          git clone https://github.com/hydephp/hyde.git --depth 1
          cp bladedown/tests/runner/composer.json hyde/composer.json
          sed -i "s/hyde\/bladedown\": \"dev-main\"/hyde\/bladedown\": \"dev-${GITHUB_SHA}\"/g" hyde/composer.json
          rm hyde/_pages/*

      - name: Install test environment
        working-directory: hyde
        run: composer install --no-interaction --no-progress --no-dev

      - name: Copy test fixtures
        run: cp -r bladedown/tests/fixtures/. hyde/_pages

      - name: Test site can be built
        working-directory: hyde
        run: php hyde build --no-ansi

      - name: Assert pages were created
        run: |
            test -f hyde/_site/index.html
